spring.application.name=config-server
server.port=8888

# Config Server Native File Backend
spring.profiles.active=native

# Local development
# spring.cloud.config.server.git.uri=file://${user.dir}/config-repo

# inside docker
spring.cloud.config.server.native.searchLocations=file:///app/config-repo

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,env
management.endpoint.health.show-details=always
