spring.application.name=config-server
server.port=8888

# Config Server Configuration
spring.cloud.config.server.git.uri=file://${user.dir}/config-repo
spring.cloud.config.server.git.default-label=master
spring.cloud.config.server.git.clone-on-start=true
